//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PPI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PPITYPE                     129
#define IDD_DIALOG1                     130
#define IDC_BUTTON1                     1000
#define IDC_DENSITY                     1001
#define IDC_CLUSTERPROPERTY             1002
#define IDC_READDATA                    1003
#define IDC_DRAWGRAPH                   1004
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
